server:
  port: 8082

# Temporary non-functional comment1
# Temporary non-functional comment2
# Temporary non-functional comment3
spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/order_db}
    username: ${DB_USERNAME:order_user}
    password: ${DB_PASSWORD:order_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8081}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs

